"""Standalone drum detector prototype for SampleRod."""

from .analyzer import (
    DEFAULT_SPLIT_DENSITY,
    DrumCandidate,
    DrumDetectionResult,
    HitSequence,
    HitSequenceEvent,
    TransientHit,
    analyze_file,
    analyze_file_from_markers,
    detect_drum_from_audio,
    detect_drum_from_markers,
    requantize_detection_result,
)
from .pattern_generator import (
    BreakPatternParams,
    GeneratedBreakPattern,
    GeneratedPatternStep,
    UserMotif,
    estimate_pattern_effect_probabilities,
    estimate_pattern_family_probabilities,
    estimate_user_motif_effective_probability,
    generate_break_pattern,
    generate_break_pattern_hybrid,
    reroll_break_pattern_step,
)
from .preview import RetimedPreview, RetimedPreviewSegment, build_retimed_preview

__all__ = [
    "BreakPatternParams",
    "DrumCandidate",
    "DrumDetectionResult",
    "GeneratedBreakPattern",
    "GeneratedPatternStep",
    "HitSequence",
    "HitSequenceEvent",
    "RetimedPreview",
    "RetimedPreviewSegment",
    "TransientHit",
    "UserMotif",
    "analyze_file",
    "analyze_file_from_markers",
    "build_retimed_preview",
    "DEFAULT_SPLIT_DENSITY",
    "detect_drum_from_audio",
    "detect_drum_from_markers",
    "estimate_pattern_effect_probabilities",
    "estimate_pattern_family_probabilities",
    "estimate_user_motif_effective_probability",
    "generate_break_pattern",
    "generate_break_pattern_hybrid",
    "requantize_detection_result",
    "reroll_break_pattern_step",
]
